version: 0.1
project:
  id: lattice-base
  name: lattice-base
  owner: nosimpler@gmail.com
  description: 'Core lattice model + CLI for project/task dependency graphs, with
    YAML I/O and Mermaid export, intended as a lightweight dependency backbone for
    projects like neurd-org and neurd-model-service.

    '
  statuses:
  - suggested
  - design
  - planned
  - in-progress
  - done
  - blocked
  lattice_version: 0.1.0
  package_version: null
  test: null
tasks:
- id: epic-core
  name: Core lattice model & I/O
  kind: epic
  status: null
  priority: null
  depends_on: []
  tags:
  - core
  - schema
  - io
  description: 'Pydantic model for project lattices and YAML load/save utilities.
    This underpins all CLI tools and integrations.

    '
  test: null
  extra: {}
- id: lb-core-model
  name: Pydantic lattice model
  kind: task
  status: done
  priority: high
  depends_on: []
  tags:
  - core
  - schema
  - epic:core
  description: 'Implement the Lattice, ProjectMeta, and Task models in model.py, including
    support for kinds (task, epic, subproject, completion), statuses, priority, test
    commands, and extra fields.

    '
  test: pytest tests/test_model.py::test_lattice_roundtrip
  extra: {}
- id: lb-core-io
  name: YAML load/save helpers
  kind: task
  status: done
  priority: high
  depends_on:
  - lb-core-model
  tags:
  - core
  - io
  - epic:core
  description: 'Implement load_lattice and save_lattice helpers in io.py, ensuring
    that project.yaml can be round-tripped without losing information.

    '
  test: pytest tests/test_io.py::test_load_save_roundtrip
  extra: {}
- id: lb-core-validation
  name: Basic validation semantics
  kind: task
  status: done
  priority: high
  depends_on:
  - lb-core-model
  - lb-core-io
  tags:
  - core
  - validation
  - epic:core
  description: 'Define core validation semantics (no unknown depends_on ids, acyclic
    graph, and test required for certain statuses/kinds) without involving any UI
    or external systems.

    '
  test: pytest tests/test_validate.py::test_basic_validation_rules
  extra: {}
- id: epic-graph
  name: Graph reasoning & analysis
  kind: epic
  status: null
  priority: null
  depends_on: []
  tags:
  - graph
  - analysis
  description: 'Functions for computing ready tasks, topological order, and edges,
    used by CLI tools and future visualizers.

    '
  test: null
  extra: {}
- id: lb-graph-ready
  name: Ready task computation
  kind: task
  status: done
  priority: high
  depends_on:
  - lb-core-model
  tags:
  - graph
  - scheduling
  - epic:graph
  description: 'Implement compute_ready_tasks to identify tasks that can be started
    now, given current task statuses and dependency structure.

    '
  test: pytest tests/test_graph.py::test_compute_ready_tasks
  extra: {}
- id: lb-graph-toposort
  name: Topological sort & cycle detection
  kind: task
  status: done
  priority: medium
  depends_on:
  - lb-core-model
  tags:
  - graph
  - topo
  - epic:graph
  description: 'Implement topological_sort and related utilities to detect cycles
    and produce a valid build order over tasks.

    '
  test: pytest tests/test_graph.py::test_topological_sort_and_cycle_detection
  extra: {}
- id: epic-cli
  name: CLI suite
  kind: epic
  status: null
  priority: null
  depends_on: []
  tags:
  - cli
  description: 'Command-line tools for initializing, inspecting, validating, and visualizing
    lattices, all built on top of the core model & graph.

    '
  test: null
  extra: {}
- id: lb-cli-init
  name: lattice-base-init
  kind: task
  status: done
  priority: high
  depends_on:
  - lb-core-model
  - lb-core-io
  tags:
  - cli
  - init
  - epic:cli
  description: 'Implement lattice-base-init, which creates a minimal project.yaml
    given a repo root, project id, and name, without overwriting existing files.

    '
  test: pytest tests/test_cli_init.py::test_init_creates_project_yaml
  extra: {}
- id: lb-cli-next
  name: lattice-base-next
  kind: task
  status: done
  priority: high
  depends_on:
  - lb-core-model
  - lb-graph-ready
  tags:
  - cli
  - scheduling
  - epic:cli
  description: 'Implement lattice-base-next to list tasks that are ready to start
    (kind=task, not done/blocked, and all dependencies done).

    '
  test: pytest tests/test_cli_next.py::test_lists_ready_tasks
  extra: {}
- id: lb-cli-validate
  name: lattice-base-validate
  kind: task
  status: done
  priority: high
  depends_on:
  - lb-core-validation
  - lb-graph-toposort
  tags:
  - cli
  - validation
  - epic:cli
  description: 'Implement lattice-base-validate to perform core validation checks
    on project.yaml and exit non-zero on errors. '
  test: pytest tests/test_cli_validate.py::test_reports_validation_errors
  extra: {}
- id: lb-cli-mermaid
  name: lattice-base-mermaid
  kind: task
  status: done
  priority: high
  depends_on:
  - lb-core-model
  - lb-graph-ready
  tags:
  - cli
  - mermaid
  - visualization
  - epic:cli
  description: 'Implement lattice-base-mermaid to emit a Mermaid graph of the lattice
    suitable for embedding directly into GitHub/Markdown documentation. '
  test: pytest tests/test_cli_mermaid.py::test_mermaid_output_non_empty
  extra: {}
- id: lb-cli-test
  name: lattice-base-test CLI
  kind: task
  status: done
  priority: high
  depends_on:
  - lb-core-model
  - lb-core-io
  tags:
  - cli
  - tests
  - epic:cli
  description: 'Implement the lattice-base-test command to run a task''s test command
    and optionally mark the task as done when the test passes. '
  test: pytest tests/test_cli_test.py::test_main_test_marks_done_on_success
  extra: {}
- id: epic-dx
  name: Documentation & DX
  kind: epic
  status: null
  priority: null
  depends_on: []
  tags:
  - docs
  - dx
  description: 'Documentation, quickstarts, and guidance for using lattice-base in
    projects like neurd-org and neurd-model-service. '
  test: null
  extra: {}
- id: lb-dx-readme
  name: Core README & examples
  kind: task
  status: done
  priority: medium
  depends_on:
  - lb-cli-init
  - lb-cli-next
  - lb-cli-validate
  - lb-cli-mermaid
  tags:
  - docs
  - readme
  - epic:dx
  description: 'Write a README that explains the lattice model, basic semantics, and
    shows examples of using the CLI tools, including quickstarts.

    '
  test: pytest tests/test_docs.py::test_readme_mentions_cli_tools
  extra: {}
- id: lb-dx-quickstart-windows
  name: Windows quickstart
  kind: task
  status: done
  priority: medium
  depends_on:
  - lb-dx-readme
  tags:
  - docs
  - windows
  - epic:dx
  description: 'Ensure the README includes a working Windows/PowerShell quickstart
    with venv creation and lattice-base CLI usage.

    '
  test: pytest tests/test_docs.py::test_windows_quickstart_snippet_present
  extra: {}
- id: lb-dx-quickstart-linux
  name: Linux/macOS quickstart
  kind: task
  status: done
  priority: medium
  depends_on:
  - lb-dx-readme
  tags:
  - docs
  - linux
  - macos
  - epic:dx
  description: 'Ensure the README includes a working Linux/macOS quickstart with venv
    creation and lattice-base CLI usage.

    '
  test: pytest tests/test_docs.py::test_linux_quickstart_snippet_present
  extra: {}
- id: lb-dx-bootstrap-scripts
  name: Bootstrap scripts for user repos
  kind: task
  status: done
  priority: medium
  depends_on:
  - lb-dx-readme
  - lb-dx-quickstart-windows
  - lb-dx-quickstart-linux
  tags:
  - docs
  - dx
  - scripts
  - epic:dx
  description: 'Provide bootstrap scripts for Windows and Unix that create a venv,
    install lattice-base, initialize a lattice, and run validate/test/mermaid.

    '
  test: pytest tests/test_quickstart_scripts.py
  extra: {}
- id: epic-future
  name: Future features & lattice semantics
  kind: epic
  status: null
  priority: null
  depends_on: []
  tags:
  - future
  - semantics
  description: 'Future directions for lattice-base, including completion nodes, versioning
    helpers, code-block markers, and repo-splitting support. '
  test: null
  extra: {}
- id: lb-completion-enforcement
  name: Distinguished completion node enforcement
  kind: task
  status: suggested
  priority: medium
  depends_on:
  - lb-core-model
  - lb-cli-validate
  tags:
  - completion
  - semantics
  - epic:future
  description: 'Enforce (or at least validate) the presence of a single distinguished
    project-level completion node when declaring a project globally complete. '
  test: null
  extra: {}
- id: lb-code-markers
  name: Code-block markers by task id
  kind: task
  status: suggested
  priority: medium
  depends_on:
  - lb-core-model
  tags:
  - code
  - linking
  - epic:future
  description: 'Define a simple convention (e.g. ''# task: <id>'' comments) to link
    code blocks to lattice tasks, and build tools that can scan the repo to understand
    which code belongs to which task and eventually assist with splitting sublattices
    into new repos. '
  test: null
  extra: {}
- id: lb-bug-localization
  name: Bug localization via task markers
  kind: task
  status: suggested
  priority: high
  depends_on:
  - lb-code-markers
  tags:
  - bugs
  - analysis
  - epic:future
  description: 'Implement a tool that runs a failing test under coverage/trace, maps
    executed lines to task markers, and proposes the minimal task or sublattice that
    should own the bug, optionally creating a bugfix task with an attached MRE. '
  test: null
  extra: {}
- id: complete-lattice-base-v0
  name: lattice-base v0 completion
  kind: completion
  status: done
  priority: high
  depends_on:
  - lb-core-model
  - lb-core-io
  - lb-core-validation
  - lb-graph-ready
  - lb-graph-toposort
  - lb-cli-init
  - lb-cli-next
  - lb-cli-validate
  - lb-cli-mermaid
  - lb-dx-readme
  tags:
  - completion
  - project
  description: 'Version 0 of lattice-base is considered complete when the core model,
    I/O, graph reasoning, CLI tools, and baseline documentation are all implemented
    and the full pytest suite passes.

    '
  test: pytest
  extra: {}
